import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SessionProviderComp from './components/SessionProvider'
import AuthGuard from './components/AuthGuard'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sports',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-dark text-white`}>
        <SessionProviderComp>
          <AuthGuard>{children}</AuthGuard>
        </SessionProviderComp>
      </body>
    </html>
  )
}
